src/apex/handler.js, test/audits/apex.test.js
=> fix(apex): consider unknown failures unsuccessful

src/notfound/handler.js, test/audits/notfound.test.js, test/fixtures/notfounddata.js
=> fix: start date and end date params

package-lock.json, package.json, src/experimentation/handler.js, src/notfound/handler.js
=> fix: update rum api client

src/lhs/handler.js
This adds fullAuditRef to the SQS Message that is posted and processed by the post-audit-processor!
=> feat(lhs): add audit reference

src/common/audit.js, test/common/audit.test.js
=> fix: audit run returns expected format

src/common/audit-builder.js, src/common/audit.js, test/common/audit.test.js
Fixes #208
Checking for org-existence explicitly and throw.
=> fix: check org for every audit

src/common/audit.js, src/notfound/handler.js, src/utils/data-access.js, test/audits/notfound.test.js, test/common/audit.test.js
=> fix: update to AuditBuilder

src/common/audit.js, test/common/audit.test.js
=> fix: skip when audit is disabled

src/common/audit.js, src/lhs/lib.js, test/audits/lhs.test.js
Pass site object to audit runners for easy access.
=> fix: pass site to runners

package-lock.json, package.json, src/support/utils.js, test/utils/rum-utils.test.js
Fixes the rum domain key retrieval issue.
This is how to use:
```js
import { getRUMDomainkey } from '../support/utils.js';
async function auditRunner(auditUrl, context, site) {
const domainKey = await getRUMDomainkey(site.getBaseURL(), context);
...
}
```
=> fix: customer secret retrieval

src/experimentation-ess/common.js
For some of the experiments, same variant is shown in multiple urls, depending on the order that comes first, will be added to experiments in the schema. Because of this, we won't have the actual url for those variants. This is an edge case though!
When the RUM data shows same variant with different urls, use the variant with url that has more views, so that's more reliable.
[SITES-23105](https://jira.corp.adobe.com/browse/SITES-23105)
=> fix: Aggregation logic for the variants is wrong in the report

package-lock.json, package.json, src/index.js, test/index.test.js
Use `sqsEventAdapter` from shared, relates to https://github.com/adobe/spacecat-shared/issues/181
=> fix: use shared sqsEventAdapter

src/cwv/handler.js, test/audits/cwv.test.js, test/fixtures/rum-data.js
=> fix: audit context includes interval info

default.json
part 2 https://docs.renovatebot.com/self-hosted-configuration/#npmjs-registry-token-example
=> chore: renove secrets remove

package-lock.json, package.json
for `Improve granularity of high organic traffic audit`
=> chore(deps): updating rum-api-client minor release

src/forms-opportunities/handler.js, test/fixtures/expectedformvitalsdata.json, test/fixtures/formvitalsdata.json
=> enhancement: handling cwv grouping changes

src/forms-opportunities/handler.js, test/fixtures/expectedformvitalsdata.json
fix: handling cwv grouping changes and remove type key
=> fix: handling cwv grouping changes and remove type key

src/experimentation-opportunities/experimentation-opportunities.js, test/audits/experimentation-opportunities.test.js, test/fixtures/statistics-lambda-llm-insights-response.json
=> fix: handle error from llm response while updating recommendations in opportunities

src/utils/data-access.js, test/audits/backlinks.test.js, test/utils/data-access.test.js
Fix buildKey not using data property.
=> fix: syncSuggestions buildKey usage

src/experimentation-opportunities/experimentation-opportunities.js, test/audits/experimentation-opportunities.test.js, test/fixtures/expected-opportunities-data.json, test/fixtures/opportunitiesdata.json
=> fix: add opportunityImpact to rage click opportunities

README.md
adds extra error logging to the oppty creation part in the README
=> docs(readme): oppty conversion error logging

src/experimentation-opportunities/experimentation-opportunities.js, test/audits/experimentation-opportunities.test.js
=> fix: update the existing opportunity instead of removing

README.md, src/structured-data/handler.js, test/audits/structured-data.test.js, test/fixtures/structured-data/audit.json, test/fixtures/structured-data/oppty.json, test/fixtures/structured-data/structured-data.json, test/fixtures/structured-data/suggestions.json, test/shared.js
Introduce the new opportunity and suggestions data model for the structured data audit
=> feat: introduce structured data to opportunity and suggestions

src/experimentation-opportunities/experimentation-opportunities.js, test/audits/experimentation-opportunities.test.js
=> fix(experimentation-opportunities): decrease the interval to 7 days

src/backlinks/handler.js, test/audits/backlinks.test.js
=> fix: removed sendMessage for broken-backlinks

src/metatags/handler.js, test/audits/metatags.test.js
=> fix: scraper bucket env variable for meta-tags

package-lock.json, package.json
=> fix(deps): bump rum-api-client to 2.18.7

package-lock.json, package.json
=> fix(deps): bump rum-api-client to 2.18.8

src/metatags/seo-checks.js, test/audits/metatags.test.js
=> fix: sites-28312 removed duplicates field

src/forms-opportunities/handler.js, src/forms-opportunities/opportunityHandler.js, src/forms-opportunities/utils.js, test/audits/forms.test.js, test/fixtures/high-form-views-low-conversions.js
=> feat: add high-form-views-low-conversions opportunity

package-lock.json, package.json
=> fix(deps): bump rum-api-client to 2.18.9

src/sitemap/handler.js, test/audits/sitemap.test.js
=> feat: sitemap fetch finalUrl

src/forms-opportunities/opportunityHandler.js, src/forms-opportunities/utils.js, test/fixtures/high-form-views-low-conversions.js
=> fix: minor fixes to forms opportunity

src/sitemap/handler.js
=> fix: user agent for sitemap

src/backlinks/handler.js, test/audits/backlinks.test.js
Fixing issue where the site url does not display in slack reports
=> fix: site's url not displaying in slack reports

src/common/audit-utils.js, test/common/audit-utils.test.js, test/common/step-audit.test.js
=> fix: send continuation message to sqs in add step

src/forms-opportunities/handler.js, src/support/utils.js, test/support/utils.test.js
=> fix: fetch file handling for scraper result

src/forms-opportunities/highPageViewsLowFormNavOpportunity.js, src/forms-opportunities/opportunityHandler.js, src/forms-opportunities/utils.js, test/fixtures/high-form-views-low-conversions.js
=> fix: forms opportunity bug fixes

src/image-alt-text/handler.js
- https://jira.corp.adobe.com/browse/ASSETS-47849
=> fix: filter out images with nullish sources

src/forms-opportunities/utils.js, test/audits/forms.test.js, test/fixtures/high-form-views-low-conversions.js
=> fix: update forms oppoty schema

src/forms-opportunities/highPageViewsLowFormNavOpportunity.js, test/audits/forms.test.js
=> fix: update guidance for existing low form navigation oppoty

src/forms-opportunities/utils.js
=> fix: forms presigned url expiry time change

src/forms-opportunities/utils.js, test/audits/forms.test.js, test/fixtures/formscrapedata.js
=> fix: forms opportunity handling for search forms

src/metatags/handler.js
Removing a debug log that got added to main branch by mistake.
=> fix: remove debug log

src/metatags/handler.js
=> fix: metatags proper url resolution

src/forms-opportunities/opportunityHandler.js, test/fixtures/high-form-views-low-conversions.js
=> fix: update title for forms opporty

src/image-alt-text/opportunityHandler.js, test/audits/image-alt-text/opportunity-handler.test.js
- Try/catch the API call
- Default to returning 0 for both traffic metrics in that case
- [ASSETS-48423 | [BE+UI] Fallback for when there's no RUM data](https://jira.corp.adobe.com/browse/ASSETS-48423)
- [ASSETS-47238 | Alt text audit for Project Success Studio](https://jira.corp.adobe.com/browse/ASSETS-47238)
=> fix: Prevent alt-text audit from failing when RUM has no data for site

src/backlinks/kpi-metrics.js, test/audits/backlinks.test.js
Fix broken backlinks opportunity creation if there is no RUM data available
=> fix: kpi deltas undefined value

src/forms-opportunities/utils.js
=> fix: forms screenshot url expiration

src/forms-opportunities/opportunityHandler.js, src/forms-opportunities/utils.js, test/audits/forms.test.js
=> feat: modifying criteria to exclude login and signup forms for forms oppty

src/forms-opportunities/handler.js, src/forms-opportunities/utils.js, test/audits/forms.test.js, test/fixtures/expectedformsendtoscraperdata.json, test/fixtures/expectedformvitalsdata.json
=> fix: adding forms constants at common place and refactoring methods

.releaserc.cjs
=> fix: semantic release

README.md, populate-env.sh, src/index-local.js, template.yml
=> fix: fixes running audits locally for new env setup

.nycrc.json, src/forms-opportunities/opportunityHandler.js, src/forms-opportunities/oppty-handlers/guidance:high-form-views-low-conversions.js, src/index.js, test/audits/forms.test.js, test/audits/guidanceHighFormViewsLowConversions.test.js
=> feat: forms mystique integration

src/forms-opportunities/constants.js, src/forms-opportunities/handler.js, src/forms-opportunities/oppty-handlers/low-conversion-handler.js, src/forms-opportunities/oppty-handlers/low-navigation-handler.js, src/forms-opportunities/utils.js, test/audits/forms.test.js, test/fixtures/formscrapedata.js, test/fixtures/high-form-views-low-conversions.js
=> chore: forms opportunities refactoring

src/forms-opportunities/oppty-handlers/guidance-high-form-views-low-conversions.js, test/audits/guidanceHighFormViewsLowConversions.test.js
=> fix: adding oppty type check in forms guidance

src/forms-opportunities/constants.js, src/forms-opportunities/oppty-handlers/low-conversion-handler.js, src/forms-opportunities/oppty-handlers/low-navigation-handler.js, test/audits/forms.test.js, test/audits/guidanceHighFormViewsLowConversions.test.js
=> fix: forms guidance constants

src/forms-opportunities/handler.js, test/fixtures/forms/expectedformsendtoscraperdata.json, test/fixtures/forms/expectedformvitalsdata.json
=> fix: eliminating cwv data from forms audit

src/forms-opportunities/utils.js, test/audits/forms/utils.test.js
=> fix: adding field count check for forms oppoty to eliminate forms with zero fields

src/forms-opportunities/formcalc.js, src/forms-opportunities/utils.js, test/audits/forms/utils.test.js, test/fixtures/forms/expectedformsendtoscraperdata.json
=> fix: adding extra check to filter search forms in forms oppoty

src/image-alt-text/auditEngine.js
Removes new lines, tabs and extra spaces
=> fix: removes extra characters from body when using locale detection

src/image-alt-text/suggestionsEngine.js
- [ASSETS-51039](https://jira.corp.adobe.com/browse/ASSETS-51039) | Find a solution for too long audits running into lambda's 15min timeout
- [ASSETS-47238](https://jira.corp.adobe.com/browse/ASSETS-47238) | [EPIC] Alt text audit for Project Success Studio
=> Fix | Reduce alt-text audit time

src/image-alt-text/handler.js
Forces deployment of https://github.com/adobe/spacecat-audit-worker/pull/832
- [ASSETS-51039](https://jira.corp.adobe.com/browse/ASSETS-51039) | Find a solution for too long audits running into lambda's 15min timeout
- [ASSETS-47238](https://jira.corp.adobe.com/browse/ASSETS-47238) | [EPIC] Alt text audit for Project Success Studio
=> fix: force prod deployment of reduce alt-text audit PR

README.md
=> minor updates on how to run SpaceCat audits locally

src/forms-opportunities/oppty-handlers/low-conversion-handler.js, src/forms-opportunities/utils.js, test/audits/forms/low-nav-oppoty-handler.test.js, test/audits/forms/low-views-oppoty-handler.test.js, test/fixtures/forms/high-form-views-low-conversions.js
=> feat: adding form view rate for forms oppty

src/common/step-audit.js, src/forms-opportunities/handler.js, test/fixtures/forms/expectedformsendtoscraperdata.json
=> fix: passing allowCache to content scraper audit step from forms handler

src/forms-opportunities/formcalc.js, src/forms-opportunities/utils.js, test/audits/forms/low-nav-oppoty-handler.test.js, test/fixtures/forms/high-form-views-low-conversions.js
=> feat: forms iframeSrc

test/audits/forms/low-nav-oppoty-handler.test.js
=> fix: code conflicts for iframe

src/experimentation-opportunities/handler.js
Fixes [SITES-31752](https://jira.corp.adobe.com/browse/SITES-31752)
=> fix: missing audit id in messages sent to mystique

src/forms-opportunities/oppty-handlers/low-conversion-handler.js, src/forms-opportunities/oppty-handlers/low-navigation-handler.js, src/forms-opportunities/oppty-handlers/low-views-handler.js, test/audits/forms/oppty-handlers/low-nav-oppoty-handler.test.js, test/audits/forms/oppty-handlers/low-views-oppoty-handler.test.js, test/fixtures/forms/high-form-views-low-conversions.js
=> fix: update tags and title in forms oppoty

test/audits/internal-links/handler.test.js
=> test: fix internal broken backlinks tests

src/preflight/handler.js, test/audits/preflight.test.js
=> feat: introduce bad-links

src/forms-opportunities/formcalc.js
=> fix: removing dialog from formsource selector if exists

src/forms-opportunities/utils.js, test/audits/forms/utils.test.js
=> feat: filter forms with only single button

src/forms-opportunities/formcalc.js, src/forms-opportunities/oppty-handlers/low-conversion-handler.js, src/forms-opportunities/utils.js, test/audits/forms/oppty-handlers/low-conv-oppoty-handler.test.js, test/fixtures/forms/high-form-views-low-conversions.js
=> fix: traffic data inclusion in form low conv oppoty

src/forms-opportunities/oppty-handlers/low-views-handler.js, test/audits/forms/oppty-handlers/low-views-oppoty-handler.test.js
=> feat: low view mystique bug fix: send mandatory params

src/forms-opportunities/oppty-handlers/low-navigation-handler.js, src/forms-opportunities/oppty-handlers/low-views-handler.js, test/audits/forms/oppty-handlers/low-views-oppoty-handler.test.js
=> fix: update tags in low view forms oppoty and fix NaN

src/forms-opportunities/guidance-handlers/guidance-high-form-views-low-conversions.js, src/forms-opportunities/guidance-handlers/guidance-high-page-views-low-form-nav.js, src/forms-opportunities/guidance-handlers/guidance-high-page-views-low-form-views.js, test/audits/forms/guidance-handlers/guidance-high-form-views-low-conversions.test.js, test/audits/forms/guidance-handlers/guidance-high-page-views-low-form-nav.test.js, test/audits/forms/guidance-handlers/guidance-high-page-views-low-form-views.test.js
=> feat: form source will be sent as camel case from mystique

src/forms-opportunities/guidance-handlers/guidance-accessibility.js, src/forms-opportunities/oppty-handlers/accessibility-handler.js, test/audits/forms/accessibility-handler.test.js, test/audits/forms/guidance-handlers/guidance-accessibility.test.js
=> fix: error due to invalid access from opportunity object

src/forms-opportunities/oppty-handlers/low-conversion-handler.js, src/forms-opportunities/oppty-handlers/low-navigation-handler.js, test/fixtures/forms/high-form-views-low-conversions.js
=> fix: add form_source and remove screenszshot prop from M msg

src/forms-opportunities/utils.js, test/audits/forms/utils.test.js
=> fix: forms a11y code

src/forms-opportunities/handler.js, test/fixtures/forms/expectedformsendtoscraperdata.json
=> fix: allowing scraper cache for forms

src/forms-opportunities/oppty-handlers/low-navigation-handler.js, src/forms-opportunities/oppty-handlers/low-views-handler.js
=> fix: checking before overwriting forms guidances

src/backlinks/handler.js, test/audits/backlinks.test.js
https://jira.corp.adobe.com/browse/SITES-32213
=> fix:broken-backlinks auto-identify should work even when no top-pages

package-lock.json, package.json, src/preflight/handler.js, test/audits/preflight.test.js
=> fix: adding promise token handling

src/geo-brand-presence/handler.js, test/audits/geo-brand-presence.test.js
- https://jira.corp.adobe.com/browse/LLMO-36
=> feat: geo presence: only trigger detection

package.json, src/paid/guidance-handler.js, src/paid/guidance-opportunity-mapper.js, src/paid/handler.js, test/audits/paid/guidance.test.js, test/audits/paid/opportunity-mapper.test.js
https://jira.corp.adobe.com/browse/SITES-32826
creates or updates opportunity based on data from mystique
=> feat: save paid cookie consent opp

src/cdn-logs-report/constants/sheet-configs.js, src/cdn-logs-report/constants/topic-patterns.js, test/audits/cdn-logs-report/sheet-configs.test.js, test/audits/cdn-logs-report/topic-patterns.test.js
Add proper products topic regex for bacom
=> fix: add proper products regex for bacom

src/preflight/metatags.js, test/audits/preflight.test.js
=> fix: running preflight for root pages

package-lock.json, package.json, src/index.js, src/page-intent/handler.detect.js, test/audits/page-intent/page-intent.detect.test.js
=> feat: page intent detect handler

src/preflight/handler.js, test/audits/preflight.test.js
=> fix: fixing preflight audit for root pages

src/cdn-analysis/sql/akamai/create-raw-table.sql, src/cdn-analysis/sql/akamai/unload-aggregated.sql, src/cdn-analysis/sql/fastly/create-raw-table.sql, src/cdn-analysis/sql/fastly/unload-aggregated.sql, src/cdn-logs-report/sql/create-aggregated-table.sql
Add country and response time related fields
=> fix: add TTFB related fields

src/structured-data/handler.js, test/audits/structured-data/structured-data.test.js
Fix for https://jira.corp.adobe.com/browse/SITES-33562
=> fix: Suggestion error IDs are not unique in Structured Data Audit

package-lock.json, package.json, src/structured-data/lib.js
See https://github.com/adobe/structured-data-validator/pull/31 for details.
=> fix: Upgrade @adobe/structured-data-validator to version 1.2.4

CHANGELOG.md, package-lock.json, package.json, src/accessibility/utils/data-processing.js, src/accessibility/utils/scrape-utils.js, src/forms-opportunities/oppty-handlers/accessibility-handler.js, test/audits/forms/accessibility-handler.test.js
=> Mayankjindalmj patch 1 1

src/image-alt-text/handler.js
Avoid sending duplicate page URLs to mystique.
=> fix: send unique page url

package-lock.json, package.json
=> chore(deps): Update spacecat-shared-data-access to latest 2.45.0

package-lock.json, package.json
=> fix(deps): Update spacecat-shared-data-access to 2.53.0

test/common/step-audit.test.js
=> fix: failing tests

package-lock.json, package.json, src/common/runner-audit.js, src/llmo-referral-traffic/handler.js, test/audits/preflight.test.js
=> feat: run llmo-referral-traffic for specific week

src/internal-links/handler.js
=> fix: broken internal links auto-suggest

CHANGELOG.md, package-lock.json, package.json
=> force push

src/preflight/accessibility.js
=> change polling interval to 1s

src/geo-brand-presence/handler.js
https://jira.corp.adobe.com/browse/LLMO-19
https://jira.corp.adobe.com/browse/LLMO-36
https://jira.corp.adobe.com/browse/LLMO-185
=> feat: More explicit error logging for geo presence audit

src/cdn-logs-report/constants/topic-patterns.js
=> fix: fix lint issues with topic-patterns

src/cdn-logs-report/constants/country-patterns.js, src/cdn-logs-report/sql/agentic-traffic-report.sql
- Reduce size of excel by grouping urls for status 2xx and 3xx
- make country patterns - case insensitive
=> fix: reduce size of excel by grouping urls for status 2xx and 3xx

src/cdn-analysis/handler.js, src/cdn-analysis/sql/cloudflare/create-database.sql, src/cdn-analysis/sql/cloudflare/create-raw-table.sql, src/cdn-analysis/sql/cloudflare/unload-aggregated.sql, test/audits/cdn-analysis/handler.test.js
=> feat: add Cloudflare CDN support

.nycrc.json, src/canonical/handler.js
=> fix: preflight canonical check failing with extensions

src/paid-traffic-analysis/cache-warmer.js, test/audits/paid-traffic-analysis/cache-warmer.test.js, test/audits/paid-traffic-analysis/handler.test.js
=> fix: use correct bucket env

src/backlinks/opportunity-data-mapper.js, src/cwv/opportunity-data-mapper.js, src/image-alt-text/handler.js, test/fixtures/cwv/oppty.json
- Remove GSC data source where not required.
JIRA: https://jira.corp.adobe.com/browse/SITES-34691
=> chore: remove gsc data source where not required

package-lock.json, package.json, src/cdn-analysis/handler.js, src/cdn-analysis/sql/akamai/unload-aggregated-referral.sql, src/cdn-analysis/sql/akamai/unload-aggregated.sql, src/cdn-analysis/sql/cloudflare/unload-aggregated-referral.sql, src/cdn-analysis/sql/cloudflare/unload-aggregated.sql, src/cdn-analysis/sql/fastly/unload-aggregated-referral.sql, src/cdn-analysis/sql/fastly/unload-aggregated.sql, src/cdn-logs-report/constants/report-configs.js, src/cdn-logs-report/constants/sheet-configs.js, src/cdn-logs-report/handler.js, src/cdn-logs-report/sql/create-aggregated-referral-table.sql, src/cdn-logs-report/sql/create-aggregated-table.sql, src/cdn-logs-report/utils/query-builder.js, src/cdn-logs-report/utils/report-utils.js, src/utils/cdn-utils.js, src/utils/data-access.js, test/audits/cdn-analysis/handler.test.js, test/audits/cdn-logs-report/handler.test.js, test/audits/cdn-logs-report/query-builder-referral.test.js, test/audits/cdn-logs-report/query-builder.test.js, test/audits/cdn-logs-report/sheet-configs.test.js, test/utils/cdn-utils.test.js, test/utils/data-access.test.js
S3 - restructure to use single bucket for CDN logs
=> feat: s3 restructure to use single bucket for CDN logs

src/llmo-customer-analysis/handler.js
=> fix(llmo-customer-analysis): properly define options for not taking screenshots

src/llmo-customer-analysis/domain-analysis.js, src/llmo-customer-analysis/handler.js, src/llmo-customer-analysis/product-analysis.js, src/llmo-customer-analysis/utils.js
- fix(llmo-customer-analysis): add step for OpTel import
- fix(llmo-customer-analysis): limit the number of pages to scrape and the parts of the scrapes to analyze
- fix(llmo-customer-analysis): use correct base URL for scrapes; avoid overwriting files
=> fix(llmo-customer-analysis): add step for OpTel import

src/common/opportunity.js, src/csp/csp-auto-suggest.js, src/csp/csp.js, test/audits/csp.test.js
Changes:
- include relative url in CSP findings JSON
- adjust how-to-fix message
=> fix: minimal CSP data format adjustment

package.json, src/preflight/handler.js, test/audits/preflight.test.js, test/fixtures/preflight/preflight-identify-readability.json, test/fixtures/preflight/preflight-identify.json, test/fixtures/preflight/preflight-suggest.js
=> fix: [preflight] updating lorem-ipsum check name

src/llm-error-pages/guidance-handler.js, src/llm-error-pages/handler.js, src/llm-error-pages/utils.js, test/audits/llm-error-pages/guidance-handler.test.js
- Removed matching of UAs from spacecat to mystique, suggestions are now updated if the URL matches.
=> fix: updating response handling from mystique to spacecat

src/preflight/handler.js
=> fix: revert lorem ipsum check for preflight

src/cdn-logs-report/constants/user-agent-patterns.js, src/cdn-logs-report/utils/query-builder.js
=> feat: add support for google ai

src/cdn-logs-report/handler.js
Add support for current Weekoffset
=> fix: support current weekoffset

src/cdn-logs-report/handler.js
=> fix: increase polling time for cdn report generation

src/llmo-customer-analysis/domain-analysis.js, src/llmo-customer-analysis/page-type-analysis.js, src/llmo-customer-analysis/product-analysis.js, src/llmo-customer-analysis/utils.js
=> chore(llmo-customer-analysis): use gpt client

package-lock.json, src/llmo-customer-analysis/domain-analysis.js, src/llmo-customer-analysis/handler.js, src/llmo-customer-analysis/page-type-analysis.js, src/llmo-customer-analysis/product-analysis.js, src/llmo-customer-analysis/utils.js, src/support/utils.js
- fallback to top-pages import if OpTel cannot be utilized
- prompt improvements
- add ability to perform domain analysis with URLs alone
=> feat(llmo-customer-analysis): retreive URLs from Ahref if no OpTel data is present

src/redirect-chains/handler.js, test/audits/redirect-chains.test.js
* enhanced with new suggestion type when Source URL redirects to itself
=> feat: redirect-chains audit

package.json, src/common/opportunity.js, src/headings/handler.js, src/headings/opportunity-data-mapper.js, src/utils/data-access.js, test/audits/headings.test.js
=> fix: adding headings for elmo

src/prerender/html-comparator-utils.js, src/prerender/opportunity-data-mapper.js, test/audits/prerender.test.js
=> fix: updating prerender opp name and fixed content gain

src/paid-traffic-analysis/handler.js, test/audits/paid-traffic-analysis/handler.test.js
dont set week for monthly runs
=> fix: incorrectly use of last week instead of month

src/llmo-referral-traffic/handler.js
=> fix: handle no optel data case for llmo-referral-traffic
