- src/backlinks/handler.js
- test/audits/backlinks.test.js
Broken backlinks should run only for sites that are live
> fix: run broken backlinks audit only for sites that are live

- src/support/ahrefs-client.js
- test/support/ahrefs-client.test.js
Add top pages and backlinks queries from Ahrefs to be used by the SEO pre go-live assessments and others.
http client to use can be passed via constructor and the usual `fetch` is passed in the `createFrom`. This is required as we'd want to reuse the client in the pre go-live scripts, where we use node-fetch-cache to cache the responses.
Includes also changes from https://github.com/adobe/spacecat-audit-worker/pull/215 as well
> feat: top pages and backlinks from ahrefs

- src/experimentation/handler.js
- test/audits/experimentation.test.js
- test/fixtures/experimentation-data.js
> fix: Changes for websites that do not redirect non www url to www url

- src/lhs/lib.js
- src/support/psi-client.js
- test/audits/lhs.test.js
- test/support/psi-client.test.js
Adding `serviceId` (our site id) to the call to EaaS LHSaaS). This allows retrieval of reports by site id via the [EaaS LHSaaS API](https://git.corp.adobe.com/pages/Evergreen/eaas-frontend/prod/psi/#/)
> fix: add serviceId to LHSaaS call

- package-lock.json
- package.json
- test/audits/backlinks.test.js
Uses: https://github.com/adobe/spacecat-shared/pull/251
Fix: https://jira.corp.adobe.com/browse/SITES-22464?focusedCommentId=42023088&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-42023088
Expose traffic_domain - integer (10 units) - The referring domain's estimated monthly organic traffic from search,
in order to have the "Est. traffic" value (see https://cq-dev.slack.com/archives/C05A45JBP9N/p1717513501293899?thread_ts=1717155663.015079&cid=C05A45JBP9N).
No additional cost, since we already include the property in the filter and order clause.
> fix: expose traffic_domain in the broken backlinks audit data (SITES-22464)

- README.md
- src/common/audit-builder.js
- src/common/audit.js
- test/common/audit.test.js
As per previous engineering council action item: https://git.corp.adobe.com/ExpSuccess/spacecat-infrastructure-docs/wiki/Engineering-Council#1-proposal-to-deprecate-the-post-processor---ekrem
This PR introduces the post processing step to the audit sequence in the audit-worker. Post-processor functions added are run sequentially at the end of each audit run.
Documentation: https://github.com/adobe/spacecat-audit-worker/tree/audit-post-processors?tab=readme-ov-file#how-to-add-a-custom-post-processor
> feat: audit post processors

- package-lock.json
- package.json
- src/conversion/handler.js
- src/cwv/handler.js
- src/experimentation/handler.js
- src/notfound/handler.js
- src/support/utils.js
- test/utils/rum-utils.test.js
This PR introduces:
1. `rum-api-client` v1 to v2 upgrade
2. `rum-api-client@v1` is imported as `@adobe/spacecat-shared-rum-api-client-v1` via [npm aliases](https://docs.npmjs.com/cli/v8/using-npm/package-spec#aliases) for the legacy audits using older `rum-api-client` version 
3. Since we currently are not using a "global" domain key for `v2`, a utility `getRUMDomainkey` function introduced to fetch domainkeys from AWS for specific pilot customers
> feat: rum-api-client v2 with customer specific domain key support

- src/backlinks/handler.js
- test/audits/backlinks.test.js
This PR introduces graceful error handling for the broken backlinks auto-suggest.
If the auto-suggest fails, it still returns the audit result.
In the future, auto-detect and auto-suggest should be split anyways.
> fix: gracefully handle broken backlinks suggestion error

- test/audits/backlinks.test.js
Reduce time to run tests.
Before: each test in the broken-backlinks suite that was hitting `filterOutValidBacklinks` was taking >3s to run because the setup included a broken backlink that when called was responding with a delay of 10000ms and fetch was waiting 3s for the response and then timing out.
After this fix: there's a single test that is including this case: `should filter out from audit result broken backlinks the ones that return ok (even with redirection)`.
> tests(broken-backlinks): reduce time to run tests

- src/canonical/handler.js
- test/audits/canonical.test.js
Small fix for the usecase : 
- when url.hostname has www but  base.hostname doesn't.
www.example.com vs  example.com
> fix: same domain check with www for baseUrl

- src/cwv/handler.js
- test/audits/cwv.test.js
The new RUM Bundler API needs specific type of a URL param which is different from the previous one calculated via following redirects for pagespeed API.
> fix(cwv): audit url calculating for rum bundler API

- src/experimentation-ess/all.js
- src/experimentation-ess/daily.js
Applying the fix of https://github.com/adobe/spacecat-audit-worker/pull/386 to `experimentation-ess` audits
> fix(experimentation-ess): audit url calculating for rum bundler API

- src/backlinks/handler.js
- test/audits/backlinks.test.js
Temporary fix in order to disable the not so qualitative suggestions for the current auto-suggest approach.
To be used in the future to enable selectively the improved auto-suggest approach (due to COGS).
> fix(broken-backlinks): introduce auto-suggest flag for broken backlinks suggestions

- src/internal-links/handler.js
- test/audits/internal-links.test.js
Issue: https://jira.corp.adobe.com/browse/SITES-25870
Linked PR for reporting: https://github.com/adobe/spacecat-reporting-worker/pull/47
Audit result schema updated to match with broken internal links with some differences.
Updated schema for broken internal links audit result: 
```
{
url_to: 'https://www.example.com/article/dogs/breeds/choosing-an-irish-setter',
url_from: 'https://www.example.com/article/dogs/just-for-fun/dogs-good-for-men-13-manly-masculine-dog-breeds',
traffic_domain: 100,
},
```
broken internal links result schema:
```
{
"url_suggested": "https://www.petplace.com/article/cats/pet-health/cats-and-mating",
"url_to": "https://example.com/broken-page",
"title": "Example Page Title",
"url_from": "https://referrer.com/referring-page",
"traffic_domain": 50000
}
```
Note:
- …
> fix: broken internal links result schema update

- src/metatags/handler.js
- test/audits/metatags.test.js
Meta-tags worker when called from slackbot (api-service) works fine but when it is invoked by jobs-dispatcher, the site id is undefined comes. Upon checking, found that jobs-dispatcher sends the siteId in queue message as siteId param and the api-service sends siteId as url param. Handled both in audit worker to make it working with both
> fix: using url and siteId param to fetch siteId for meta-tags audit

- src/utils/s3-utils.js
- test/audits/metatags.test.js
- test/utils/s3-utils.test.js
[[SITES-27500] Fix regarding audit-worker reading screenshot data as JSON](https://jira.corp.adobe.com/browse/SITES-27500)
> fix: modified `getObjectFromKey` to parse non JSON objects as well

- README.md
- src/common/audit.js
- test/common/audit.test.js
As discussed in the [last Engineering Council ](https://git.corp.adobe.com/ExpSuccess/spacecat-infrastructure-docs/wiki/Engineering-Council#architecture-meeting-january-9-2025), the auto-suggest feature should be a post-processing step in the `AuditBuilder`.
This requires a change in the `AuditBuilder` to be able to chain the post processors and update the auditData for them to re-use.
Also adding instructions on how to implement a new auto-suggest feature to the readme
> feat: adding auto-suggest instructions and chain post processors

- src/sitemap/handler.js
- test/audits/sitemap.test.js
Rename suggestedFix to urls_suggested to keep consistency across audits.
> fix: use urls_suggested as the suggested fix for sitemap redirects

- src/backlinks/handler.js
- src/common/audit.js
- src/index.js
adding cause to the error within a handler, to be able to retrieve the corresponding stack trace in the log
> fix: error propagation in handlers

- README.md
Updating the README.md guide on how to add Opportunities and Suggestions
> docs: updating README for adding Opportunities and Suggestions

- package-lock.json
- package.json
- src/common/step-audit.js
- test/common/step-audit.test.js
Fixes an issue where the destination configuration of stepped audits would not retrieve the correct queue URL to send the SQS message to.
> fix: step audit queue url

- src/sitemap/handler.js
- simplified the sitemap handler by removing User-Agent header settings, since there are already handled by `tracingFetch`. 
- removed the `DEFAULT_USER_AGENT` from `fetch` calls
> fix: remove user-agent from sitemap handler

- src/metatags/seo-checks.js
- test/audits/metatags.test.js
JIRA: https://jira.corp.adobe.com/browse/SITES-29433
Related slack: https://cq-dev.slack.com/archives/C05A45JBP9N/p1739989459286999
Disabling 'Multiple H1 on a page' check due to below issue:
"For the metadata opportunity, in case of multiple H1 on a page, we show the attached dialog to customer to convert one of them to H1, and others to H2. Now in this issue, there can be same H1s on the page as well in which case the customer might not be able to assess which H1 to keep and which to convert to H2. This also poses an issue with auto-fix where content sdk needs some identifier to identify which of the 2 same H1s to convert to H2."
> fix: disable multiple h1 count check for metadata

- src/support/utils.js
Some urls that we get as a response from fetch call contains path.
e.g. "www.westjet.com/en-us"
We need to trim path and trailing slash if any, from it. Thats because RUM needs urls without paths.
This is useful fix for westjet, ibm, bitdefender etc.
https://jira.corp.adobe.com/browse/SITES-27731
> Adds fix to trims any tailing path from url

- package.json
- src/image-alt-text/opportunityHandler.js
- src/image-alt-text/suggestionsEngine.js
- static/prompts/image-alt-text.prompt
- test/audits/image-alt-text/opportunity-handler.test.js
- test/audits/image-alt-text/suggestions-engine.test.js
Calls Firefall API for recommendations of missing alt-tags:
- using `gpt-4o`
- batches of 10 images
- 5000ms throttle
- For now supports only `webp|png|gif|jpeg|jpg`
https://jira.corp.adobe.com/browse/ASSETS-47238
https://jira.corp.adobe.com/browse/ASSETS-47371
> feat: adds gpt recommendations to alt-text audit

- src/metatags/handler.js
- test/audits/metatags.test.js
Slash at Urls end is not retained in meta-tags audit results
https://jira.corp.adobe.com/browse/SITES-29515
https://cq-dev.slack.com/archives/C085NJRJG2W/p1740428584585269
> One observation I had: volvo site expect a / at the end of many of their urls otherwise they respond with 'Page not found'. For ex. https://www.volvotrucks.us/about-volvo/facilities/parts-distribution-centers
On metadata opportunity UI, many urls on the page are redirecting to 'page not found' due to above issue. Looks like we need to retain the / at the end of these urls. I have created [SITES-29515](https://jira.corp.adobe.com/browse/SITES-29515) for this and am working on it. The detected metadata suggestions are all fine though.
> fix: retaining slash at Urls end in Meta-tags

- src/image-alt-text/constants.js
- src/image-alt-text/opportunityHandler.js
- test/audits/image-alt-text/opportunity-handler.test.js
Fetch real metrics from RUM and compute traffic metrics based on a formula.
- [ASSETS-47557 | [Backend] Compute real projected traffic values](https://jira.corp.adobe.com/browse/ASSETS-47557)
- [ASSETS-47238 | [Epic] Alt text audit for Project Success Studio](https://jira.corp.adobe.com/browse/ASSETS-47238)
> feat: add alt-text projected traffic metrics to opportunity

- src/metatags/constants.js
- src/metatags/handler.js
- test/audits/metatags.test.js
If the site doesn't have RUM enabled then the meta-tags audit fails as it tries to calculate projected traffic value but gets an error in rum query. In this PR, this error has been handled so that failure to calculate projected traffic doesn't fails the meta-tags audit.
> fix: handling site RUM missing for meta-tags

- src/image-alt-text/auditEngine.js
- src/image-alt-text/handler.js
- test/audits/image-alt-text/auditEngine.test.js
- test/audits/image-alt-text/handler.test.js
- [ASSETS-48652 | How to handle presentational/decorative images](https://jira.corp.adobe.com/browse/ASSETS-48652)
- [ASSETS-47238 | Alt text audit for Project Success Studio](https://jira.corp.adobe.com/browse/ASSETS-47238)
> feat: add presentational check when extracting images

- src/sitemap/handler.js
- src/support/utils.js
- test/audits/sitemap.test.js
Ticket : https://jira.corp.adobe.com/browse/SITES-30357
Details:
the sitemap audit was flagging URL that redirect to login/authentication pages as issues, suggesting alternative URLs.
Since these redirects are intentional - pages like /myaccount/ . should redirect to login pages when the user isn't authenticated.
Solution:  ignore login/authentication redirects in sitemap audit
Tested with https://www.brownthomas.com (siteId: fc2053c8-2b6e-427c-8fd1-11df77d2df26) 
Before:
```
{
"urlsSuggested": "https://www.brownthomas.com/content/brownthomas/ie/en/login.html",
"url": "https://www.brownthomas.com/myaccount/",
"statusCode": 302
}				
```
After:
- the auth and login urls are not longer showed.
> fix: ignore login/auth redirects as suggestions

- src/forms-opportunities/constants.js
- src/forms-opportunities/formcalc.js
- src/forms-opportunities/handler.js
- src/forms-opportunities/oppty-handlers/low-conversion-handler.js
- src/forms-opportunities/oppty-handlers/low-navigation-handler.js
- src/forms-opportunities/oppty-handlers/low-views-handler.js
- src/forms-opportunities/utils.js
- test/audits/forms/formcalc.test.js
- test/audits/forms/low-conv-oppoty-handler.test.js
- test/audits/forms/low-nav-oppoty-handler.test.js
- test/audits/forms/low-views-oppoty-handler.test.js
- test/fixtures/forms/formcalcaudit.js
- test/fixtures/forms/high-form-views-low-conversions.js
> feat: Low form views auto detect

- src/index.js
Audit worker message is not logged properly, showing [Object] [Object] in coralogix
> fix: message received from SQS is not getting logged properly

- src/metatags/handler.js
- test/audits/metatags.test.js
The meta-tag audit identified new opportunities for hersheyland and created new suggestions. But some of them were already ignored, e.g. “Duplicate H1” for  https://www.hersheyland.com/milk-duds and https://www.hersheyland.com/products/milk-duds-candy-5-oz-box.html. So now the same suggestion is in “Current” and “Ignored”.
The meta-tags audit identifies suggestions through key: url | issue | tagContent
The URLs in both the suggestions are different.
From old audit:
"url": "https://hersheyland.com/milk-duds",
From new audit:
"url": "www.hersheyland.com/milk-duds"
This is because there has been a [change](https://github.com/adobe/spacecat-audit-worker/pull/750) to use the new urlResolver, instead of the old noopUrlResolver, which resulted in this issue.
Use wwwUrlResolver for resolving …
> fix: urlResolver for meta-tags

- README.md
- package-lock.json
- package.json
- test/dev/server.mjs
- test/index.test.js
This update adds detailed instructions for running Spacecat audits locally using two methods:
Nodemon with AWS credentials via KLAM – includes steps for setting up .env, starting the dev server, triggering audits via curl, and viewing results in DynamoDB.
These addition aim to streamline local development and debugging for contributors.
> fix: running audits locally

- package-lock.json
- src/support/psi-client.js
- sets timeout for lhs audit to 30s. this was forgotten after our tracing fetch introduced a default timeout of 10s.
- fixes security vulns via npm audit
> fix: lhs timeout

- src/common/base-audit.js
- test/audits/metatags.test.js
- test/common/audit.test.js
`wwwUrlResolver` makes use of the `overrideBaseURL` property under site config object for the cases where audit url resolution is extremely problematic.
> fix: use base url overrides in audit url resolution

- src/forms-opportunities/formcalc.js
Reverts adobe/spacecat-audit-worker#883 due to code coverage below threshold
> Revert "fix: removing dialog from formsource selector if exists (#883)"

- src/image-alt-text/auditEngine.js
- src/image-alt-text/handler.js
- src/image-alt-text/opportunityHandler.js
- src/image-alt-text/utils.js
- test/audits/image-alt-text/audit-engine.test.js
- test/audits/image-alt-text/handler.test.js
- test/audits/image-alt-text/opportunity-handler.test.js
We have historically filtered out ALL decorative images because EDS authoring process includes empty alts `alt=""` to all images that don't have a textual alt. This effectively marks them as decorative, but they need fixing, so we allowed all decorative images to be shown as suggestions to alleviate this.
A more correct approach while the issue is not resolved in EDS, is to only show the decorative images that are so because they have an alt that is empty. This will not show other decorative images that:
- Use `aria-hidden="true"`
- Use `role="presentation"`
- [ASSETS-52117 | Filter out decorative (almost all) images from audit suggestions](https://jira.corp.adobe.com/browse/ASSETS-52117)
- [ASSETS-47238 | [EPIC] Alt …
> feat: Filter out decorative (almost all) images from audit suggestions

- src/image-alt-text/auditEngine.js
- src/image-alt-text/country-code.js
- src/image-alt-text/suggestionsEngine.js
- static/prompts/image-alt-text.prompt
- test/audits/image-alt-text/audit-engine.test.js
Add a function `detectLanguageFromUrl` to check the URL path for valid country codes and determine the language to use.
This function looks for any valid country code in the URL path segments (the parts between slashes, excluding empty segments and the last segment). If a valid country code is found, it returns the corresponding language code; otherwise, it returns null. The valid country code is defined in `country-code.js` file.
The prompt has been updated with new rules to ensure that the AI model generates alt-text in the specified language provided with each image.
- [ASSETS-52137 | Detect language from url](https://jira.corp.adobe.com/browse/ASSETS-52137)
> fix: detect language from url

- src/accessibility/utils/data-processing.js
- src/forms-opportunities/handler.js
- src/forms-opportunities/oppty-handlers/accessibility-handler.js
- src/support/utils.js
- test/audits/accessibility/data-processing.test.js
- test/audits/forms/accessibility-handler.test.js
- test/audits/forms/handler.test.js
- test/support/utils.test.js
- Modified `getObjectKeysFromSubfolders` to include a `storagePrefix` parameter for better flexibility in S3 path management.
- Refactored `createAccessibilityOpportunity`
- Updated tests to reflect changes in the accessibility opportunity creation logic and ensure proper functionality.
- Aligned storage/cleanup mechanism with the site
> fix: update accessibility data processing and opportunity creation

- src/forms-opportunities/guidance-handlers/guidance-accessibility.js
- src/forms-opportunities/handler.js
- src/forms-opportunities/oppty-handlers/accessibility-handler.js
- src/index.js
- test/audits/forms/accessibility-handler.test.js
- test/audits/forms/guidance-handlers/guidance-accessibility.test.js
- Added new guidance handlers for form accessibility.
- Introduced a new handler for processing messages from mystique regarding detected accessibility issues.
- Updated tests to cover new functionality and ensure proper handling of accessibility data.
> feat: enhance form a11y handlers to handle mystique messages

- .nycrc.json
- src/accessibility/handler.js
- src/accessibility/utils/data-processing.js
- src/accessibility/utils/scrape-utils.js
- test/audits/accessibility.test.js
- test/audits/accessibility/scrape-utils.test.js
This pull request introduces a mechanism into the accessibility audit worker to prevent the re-scraping of URLs that have already failed an audit within the same day. This is a useful measure in the context of content-scraper audits that result in timeouts due to the fixed duration of the lambda (15 min max).
Key Changes:
**accessibility/handler.js:**
- The scrapeAccessibilityData function has been updated to check for existing failed audits before dispatching a scrape request.
- It now fetches URLs from previously failed audits and filters them out from the list of URLs to be scraped.
**accessibility/utils/scrape-utils.js:**
- A new utility file has been created to house helper functions for the scraping logic.
- getExistingUrlsFromFailedAudits: This new function retrieves the keys of …
> fix: prevent re-scraping of URLs that have already failed an audit

- src/experimentation-opportunities/handler.js
- test/audits/experimentation-opportunities.test.js
Updated the variable name from 'siteAgerageCtr' to 'siteAverageCtr' in both the handler and test files to ensure consistency and accuracy in data handling.
> fix: correct typo in site average CTR variable name

- src/preflight/handler.js
- src/preflight/links-checks.js
- test/audits/preflight.test.js
- test/fixtures/preflight/preflight-identify.json
This PR adds broken external link detection to the preflight audit. When a webpage is scraped, all external links are automatically validated using HEAD requests. Broken external links (404s, network errors, timeouts) are now reported with high SEO impact and actionable recommendations.
The links audit in preflight will now return opportunities in this format:
```
{
"name": "links",
"type": "seo", 
"opportunities": [
{
"check": "broken-internal-links",
"issue": {
"url": "https://example.com/broken-page",
"issue": "Status 404",
"seoImpact": "High",
"seoRecommendation": "Fix or remove broken links to improve user experience and SEO"
}
},
{
"check": "broken-external-links", 
"issue": {
"url": "https://external-site.com/broken",
"issue": "Status error",
"seoImpact": "High", …
```
> feat: broken external links check in preflight.

- src/preflight/handler.js
The URL resolver makes an unnecessary request everytime the audit is executed, but the URL us not needed for preflight
> fix: preflight url resolver making unnecessary requests

- package-lock.json
- package.json
* Manually update dependency, as renovate PR is stuck with failing tests.
* https://github.com/adobe/structured-data-validator/pull/24
* https://github.com/adobe/structured-data-validator/pull/22
> fix(deps): update @adobe/structured-data-validator to v1.2.1

- src/accessibility/utils/generate-individual-opportunities.js
- test/audits/accessibility/generate-individual-opportunities.test.js
Added a new flag to suggesstion data object called `isCreateTicketClicked` to track if a user clicked on jira button to create a jira ticket
> feat:create-jira-ticket

- package-lock.json
- package.json
- src/preflight/links-checks.js
- test/audits/preflight.test.js
- test/fixtures/preflight/preflight-identify.json
This PR includes:
1. removes page auth token for external link checks as external links were incorrectly receiving internal authentication tokens, causing false positives when external domains returned 401/403 responses.
2. Refactored links-check to remove code duplication.
3. Fixed Internal links checks broken bug.
i. Now, checking the links that are only in main body and not in header and footer. Before when we included links that were in header and footer the total links found count was around 150 which was overloading the stream and HEAD request being too restrictive it was failing with error unexpected end of file .
ii. Added a fallback mechanism to GET request when HEAD request fails. …
> fix: remove page auth token from external link checks and fix internal link checks broken bug.

- src/image-alt-text/opportunityHandler.js
Update the `syncAltTextSuggestions` function so that it won't remove the suggestions that have FIXED status. 
[ASSETS-54507](https://jira.corp.adobe.com/browse/ASSETS-54507)
> fix: should not remove fixed suggestions

- src/accessibility/guidance-handlers/guidance-accessibility-remediation.js
- src/accessibility/handler.js
- src/accessibility/utils/data-processing.js
- src/accessibility/utils/generate-individual-opportunities.js
- src/accessibility/utils/scrape-utils.js
- test/audits/accessibility.test.js
- test/audits/accessibility/data-processing.test.js
- test/audits/accessibility/generate-individual-opportunities.test.js
- test/audits/accessibility/guidance-accessibility-remidiation.test.js
- test/audits/accessibility/scrape-utils.test.js
Add the label [A11yProcessingError] to each error log in order to have a easy query in Coralogix logs and for alerts query.
Jira ticket: https://jira.corp.adobe.com/browse/SITES-34576
> feat: add error label in the error logs for easier query

- src/accessibility/utils/generate-individual-opportunities.js
- test/audits/accessibility/generate-individual-opportunities.test.js
The purpose of this PR is to move the counting logic of the total sent suggestions before the logic responsible for updating the received suggestions with enhanced issues containing remediation details. Before, when were the suggestions counted, some of them were excluded, because they were already marked as having guidance. Now, we count the suggestions before any of them is marked as having guidance.
> fix: A11y modify the placement of sentCount metric computation

- package.json
Adding the missing static file so that audit can run in spacecat envs.
> fix: add static file for llm error pages

- src/llm-error-pages/handler.js
**Summary**: 
Normalize and resolve LLM error‑page URLs against the site base to prevent “glued host” URLs in Mystique payloads and ensure the 404 Excel file updates correctly.
**Problem**: 
We were concatenating base + rawUrl, so paths without a leading slash produced malformed URLs like https://adobe.comcreativecloud/..., which the updater couldn’t match to the sheet’s URL column.
**Fix**:
Build full URLs via resolver instead of string concatenation.
Normalize the log URL to a path before resolving against the site base.
**Example:**
Input: base https://www.adobe.com, raw creativecloud/photography/discover/bokeh.html
Old: https://www.adobe.comcreativecloud/photography/discover/bokeh.html
New: https://www.adobe.com/creativecloud/photography/discover/bokeh.html
> fix: prevent glued hosts while resolving paths

- src/cdn-analysis/sql/frontdoor/unload-aggregated-referral.sql
- src/cdn-analysis/sql/frontdoor/unload-aggregated.sql
- test/audits/cdn-logs-report/handler.test.js
exclude OTF and php extensions for Frontdoor
> fix: exclude OTF and php extensions

- src/geo-brand-presence/handler.js
- test/audits/geo-brand-presence.test.js
- Add configurable WEB_SEARCH_PROVIDERS array for sending to multiple providers
- Maintain backward compatibility: use specific aiPlatform if provided
- Extract message creation to createMystiqueMessage helper to reduce duplication
- Add safeguard for empty provider configuration
- Update tests to dynamically validate against provider array
- Export WEB_SEARCH_PROVIDERS constant for test reusability
> feat: add multi-provider support for geo-brand-presence audit
